<#
.SYNOPSIS
  Shared helper module for the whispr → cohoodOBS vault sync jobs.

.DESCRIPTION
  Dot-sourced by both `nightly-ingest.ps1` (cheap/fast per-file summarize+ingest,
  runs Mon-Fri) and `weekly-lint-compile.ps1` (expensive /lint + /compile pass,
  runs weekly). Extracted from the original single nightly-ingest.ps1 script so
  the claude-invocation plumbing, logging, and failure handling exist in exactly
  one place instead of being copy-pasted across the two jobs.

  This file MUST define ONLY functions and the $script:Utf8NoBom encoding
  object — no main-line logic runs when it is dot-sourced. Because dot-sourcing
  runs in the CALLER's scope, several functions below intentionally read
  variables the caller is responsible for setting BEFORE dot-sourcing this file
  (or before first calling the function that needs them):
    - Write-Log                reads $script:DailyLogPath
    - Invoke-ClaudeStep        reads $DryRun (the caller's -DryRun switch/param)
    - Send-BestEffortToast     no external vars, but is called via Invoke-JobFailure
    - Invoke-JobFailure        reads $LogDir, $EventLogSource, $EventLogName, $EventId

  Usage in a caller script:
    . (Join-Path $PSScriptRoot 'sync-common.ps1')
#>

# ---------------------------------------------------------------------------
# UTF-8 without BOM, matching the existing no-BOM/LF convention of both repos —
# using .NET directly here sidesteps Set-Content/Add-Content's BOM behavior
# differing between Windows PowerShell 5.1 and pwsh 7.
# ---------------------------------------------------------------------------
$script:Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
function Write-Utf8File {
    param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][AllowEmptyString()][string]$Content)
    [System.IO.File]::WriteAllText($Path, $Content, $script:Utf8NoBom)
}

function Add-Utf8Line {
    param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][AllowEmptyString()][string]$Line)
    [System.IO.File]::AppendAllText($Path, ($Line + "`n"), $script:Utf8NoBom)
}

function Write-Log {
    param(
        [ValidateSet('INFO', 'WARN', 'ERROR')][string]$Level = 'INFO',
        [Parameter(Mandatory)][string]$Message
    )
    $line = '[{0}] [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    switch ($Level) {
        'ERROR' { Write-Host $line -ForegroundColor Red }
        'WARN'  { Write-Host $line -ForegroundColor Yellow }
        default { Write-Host $line }
    }
    # Tee to the daily log file too.
    Add-Utf8Line -Path $script:DailyLogPath -Line $line
}

# ---------------------------------------------------------------------------
# Frontmatter parsing (deliberately simple line/regex based — no YAML module,
# per spec; the frontmatter here is machine-generated by whispr and always has
# a narrow, known shape). Shared between nightly-ingest.ps1 (per-transcript
# frontmatter carry-over) and weekly-lint-compile.ps1 (active-workstream
# derivation from cohoodOBS source notes) so the parsing logic exists in
# exactly one place.
# ---------------------------------------------------------------------------
function Split-Frontmatter {
    param([Parameter(Mandatory)][string]$Content)
    if ($Content -match '(?s)\A---\r?\n(.*?)\r?\n---\r?\n(.*)\z') {
        return [PSCustomObject]@{ Valid = $true; Frontmatter = $Matches[1]; Body = $Matches[2] }
    }
    return [PSCustomObject]@{ Valid = $false; Frontmatter = $null; Body = $null }
}

function ConvertFrom-YamlScalar {
    # Strips a single layer of quotes and maps a bare `null` to $null. Not a
    # real YAML parser — just enough for whispr's own generated frontmatter.
    param([AllowNull()][string]$Raw)
    if ($null -eq $Raw) { return $null }
    $t = $Raw.Trim()
    if ($t -eq '' -or $t -eq 'null') { return $null }
    if ($t -match "^'(.*)'$") { return $Matches[1] }
    if ($t -match '^"(.*)"$') { return $Matches[1] }
    return $t
}

function Get-FrontmatterScalar {
    param([Parameter(Mandatory)][string]$Frontmatter, [Parameter(Mandatory)][string]$Key)
    if ($Frontmatter -match "(?m)^$([regex]::Escape($Key)):[ \t]*(.*)$") {
        return ConvertFrom-YamlScalar -Raw $Matches[1]
    }
    return $null
}

function Get-FrontmatterListArray {
    # Generic frontmatter list-value parser: handles both flow form
    # (`key: [a, b, c]`) and block form (`key:` / `- a` / `- b`). Returns a
    # string[] (empty array if the key is absent/empty/malformed). Generalized
    # out of what used to be attendee-only parsing so callers needing a raw
    # list (weekly's topic-tag union) and callers needing a human-joined
    # string (nightly's attendees) share one parsing implementation instead of
    # duplicating the flow/block regex logic per key.
    param([Parameter(Mandatory)][string]$Frontmatter, [Parameter(Mandatory)][string]$Key)
    $escapedKey = [regex]::Escape($Key)
    if ($Frontmatter -match "(?m)^${escapedKey}:[ \t]*\[(.*)\][ \t]*`$") {
        $items = $Matches[1] -split ',' | ForEach-Object { ConvertFrom-YamlScalar -Raw $_ } | Where-Object { $_ }
        return @($items)
    }
    if ($Frontmatter -match "(?ms)^${escapedKey}:[ \t]*\r?\n((?:^-[ \t].*(?:\r?\n|\z))+)") {
        $block = $Matches[1]
        $items = [regex]::Matches($block, '(?m)^-[ \t]*(.*)$') | ForEach-Object { ConvertFrom-YamlScalar -Raw $_.Groups[1].Value } | Where-Object { $_ }
        return @($items)
    }
    return @()
}

# ---------------------------------------------------------------------------
# claude invocation
# ---------------------------------------------------------------------------
function Resolve-ClaudeExecutable {
    $cmd = Get-Command claude -ErrorAction SilentlyContinue
    if (-not $cmd) {
        throw "claude CLI not found on PATH. Install @anthropic-ai/claude-code or add it to PATH, then retry."
    }
    $source = $cmd.Source
    Write-Log -Level INFO -Message "claude resolved via Get-Command to: $source"
    if ($source -match '\.(ps1|cmd)$') {
        # Prefer the real native binary one level down (standard npm-on-Windows
        # shim layout) — gives us direct stdin/timeout/kill control without an
        # extra PowerShell/cmd host process in the way.
        $shimDir = Split-Path -Parent $source
        $candidate = Join-Path $shimDir 'node_modules\@anthropic-ai\claude-code\bin\claude.exe'
        if (Test-Path -LiteralPath $candidate) {
            Write-Log -Level INFO -Message "Using native claude.exe found alongside the shim: $candidate"
            return $candidate
        }
        Write-Log -Level WARN -Message "Native claude.exe not found next to shim; will invoke the shim itself through a host process."
        return $source
    }
    return $source
}

function New-ClaudeProcessStartInfo {
    param(
        [Parameter(Mandatory)][string]$ExePath,
        [Parameter(Mandatory)][string[]]$Args,
        [Parameter(Mandatory)][string]$WorkingDirectory
    )
    $psi = New-Object System.Diagnostics.ProcessStartInfo
    if ($ExePath -match '\.ps1$') {
        $hostCmd = Get-Command pwsh -ErrorAction SilentlyContinue
        if (-not $hostCmd) { $hostCmd = Get-Command powershell -ErrorAction SilentlyContinue }
        if (-not $hostCmd) { throw "Neither pwsh nor powershell found to host the claude.ps1 shim." }
        $psi.FileName = $hostCmd.Source
        foreach ($a in @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $ExePath) + $Args) {
            $psi.ArgumentList.Add($a)
        }
    } elseif ($ExePath -match '\.cmd$') {
        $psi.FileName = Join-Path $env:WINDIR 'System32\cmd.exe'
        foreach ($a in @('/c', $ExePath) + $Args) {
            $psi.ArgumentList.Add($a)
        }
    } else {
        $psi.FileName = $ExePath
        foreach ($a in $Args) { $psi.ArgumentList.Add($a) }
    }
    $psi.WorkingDirectory       = $WorkingDirectory
    $psi.RedirectStandardInput  = $true
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError  = $true
    $psi.UseShellExecute        = $false
    $psi.CreateNoWindow         = $true
    return $psi
}

function Invoke-ClaudeHeadless {
    # Real process invocation with a hard external timeout + kill, and the
    # prompt delivered over stdin (not argv) so we never hit the Windows
    # command-line length limit on a large transcript.
    param(
        [Parameter(Mandatory)][string]$PromptText,
        [Parameter(Mandatory)][string[]]$Args,
        [Parameter(Mandatory)][string]$WorkingDirectory,
        [Parameter(Mandatory)][int]$TimeoutSeconds
    )
    $exePath = Resolve-ClaudeExecutable
    $psi = New-ClaudeProcessStartInfo -ExePath $exePath -Args (@('-p') + $Args) -WorkingDirectory $WorkingDirectory

    $proc = New-Object System.Diagnostics.Process
    $proc.StartInfo = $psi

    try {
        $proc.Start() | Out-Null
        # Read both streams via .NET Task readers (thread-pool backed) rather than
        # PowerShell's Register-ObjectEvent/BeginOutputReadLine: those -Action
        # handlers only fire when the PS event queue is pumped, but the main thread
        # is blocked in WaitForExit() below and never pumps it — so event-based
        # capture silently yields EMPTY output even on a successful (exit 0) call.
        # ReadToEndAsync runs independently of the PS event loop and won't deadlock
        # (both streams drained concurrently).
        $outTask = $proc.StandardOutput.ReadToEndAsync()
        $errTask = $proc.StandardError.ReadToEndAsync()
        $proc.StandardInput.Write($PromptText)
        $proc.StandardInput.Close()

        $exited = $proc.WaitForExit($TimeoutSeconds * 1000)
        if (-not $exited) {
            try { $proc.Kill($true) } catch { try { $proc.Kill() } catch {} }
            $proc.WaitForExit(5000) | Out-Null
            return [PSCustomObject]@{
                Success = $false; TimedOut = $true; ExitCode = -1
                StdOut = ''; StdErr = ''
            }
        }
        # Process has exited → both streams are at EOF, so the reader tasks are
        # complete (or complete within microseconds). GetResult() gives the full
        # captured text with no event-pump dependency and no truncation.
        $stdoutText = $outTask.GetAwaiter().GetResult()
        $stderrText = $errTask.GetAwaiter().GetResult()
        return [PSCustomObject]@{
            Success = ($proc.ExitCode -eq 0); TimedOut = $false; ExitCode = $proc.ExitCode
            StdOut = $stdoutText; StdErr = $stderrText
        }
    } finally {
        $proc.Dispose()
    }
}

function Invoke-ClaudeStep {
    # Single choke point for every claude call in either script (summarize,
    # /ingest, /lint, extract-compile-targets, /compile) so DryRun handling,
    # JSON-envelope parsing, and cost tracking live in exactly one place —
    # per-step callers only supply the model/permission args and the prompt.
    param(
        [Parameter(Mandatory)][string]$StepName,
        [Parameter(Mandatory)][string]$PromptText,
        [Parameter(Mandatory)][string[]]$ExtraArgs,
        [Parameter(Mandatory)][string]$WorkingDirectory,
        [Parameter(Mandatory)][int]$TimeoutSeconds
    )
    $fullArgs = @('--output-format', 'json') + $ExtraArgs

    if ($DryRun) {
        Write-Log -Level INFO -Message "[DRYRUN] Would run claude step '$StepName' in '$WorkingDirectory' with args: $($fullArgs -join ' ')"
        $previewLines = ($PromptText -split "`n") | Select-Object -First 20
        Write-Log -Level INFO -Message "[DRYRUN] Prompt preview for '$StepName' (first 20 lines):`n$($previewLines -join "`n")"
        return [PSCustomObject]@{ Success = $true; DryRun = $true; Result = ''; CostUsd = 0.0; ExitCode = 0; StdErr = ''; TimedOut = $false }
    }

    Write-Log -Level INFO -Message "Calling claude for step '$StepName' (cwd='$WorkingDirectory', args: $($fullArgs -join ' '))"
    $proc = Invoke-ClaudeHeadless -PromptText $PromptText -Args $fullArgs -WorkingDirectory $WorkingDirectory -TimeoutSeconds $TimeoutSeconds

    $json = $null
    try { $json = $proc.StdOut | ConvertFrom-Json -ErrorAction Stop } catch { }
    $resultText = if ($json) { $json.result } else { $null }
    $costUsd = 0.0
    if ($json -and ($json.PSObject.Properties.Name -contains 'total_cost_usd') -and $null -ne $json.total_cost_usd) {
        $costUsd = [double]$json.total_cost_usd
    }

    $success = $proc.Success -and (-not $proc.TimedOut) -and (-not [string]::IsNullOrWhiteSpace($resultText))

    return [PSCustomObject]@{
        Success = $success; DryRun = $false; Result = $resultText; CostUsd = $costUsd
        ExitCode = $proc.ExitCode; StdErr = $proc.StdErr; TimedOut = $proc.TimedOut
    }
}

function ConvertFrom-ClaudeJsonLenient {
    # Tolerant JSON parse for claude extraction-step output: strips a leading
    # ```json/``` fence and trailing ``` if present (models sometimes add one
    # despite being told not to), then parses. Returns $null on any failure —
    # callers treat that as "nothing usable," not a hard error. Shared
    # primitive so any future extraction-step result shape (flat array,
    # {workstream:[],other:[]} object, etc.) reuses the same fence-stripping
    # logic instead of duplicating it. weekly-lint-compile.ps1's
    # ConvertFrom-WorkstreamSplit builds on this.
    param([AllowNull()][string]$RawResult)
    if ([string]::IsNullOrWhiteSpace($RawResult)) { return $null }
    $cleaned = $RawResult.Trim()
    $cleaned = $cleaned -replace '(?s)^```(?:json)?\s*', ''
    $cleaned = $cleaned -replace '(?s)\s*```$', ''
    try {
        return ($cleaned | ConvertFrom-Json -ErrorAction Stop)
    } catch {
        return $null
    }
}

# ---------------------------------------------------------------------------
# Sleep suppression — keep the machine out of standby for the life of the job.
# ---------------------------------------------------------------------------
function Set-SystemAwake {
    <#
      Ask Windows not to idle-sleep while this process runs.

      Added 2026-09-08 after the weekly job failed this way. The Sunday 01:00
      run never fired (machine asleep); Task Scheduler caught it up on Monday at
      12:46:30, it invoked /lint at 12:46:46, and the system entered Modern
      Standby at 12:47:51 — 65 seconds later. Everything was suspended for ~19
      hours and the 1800 s timeout fired the moment the machine woke, reported
      as "/lint call timed out". The lint was not slow; it was frozen. Any job
      here that waits on a multi-minute claude call has the same exposure.

      ES_CONTINUOUS makes the request persist rather than being a one-shot
      nudge; ES_SYSTEM_REQUIRED is what actually keeps the system up. Display
      sleep is deliberately NOT requested — the screen going dark is fine, and
      asking for ES_DISPLAY_REQUIRED on a laptop that is meant to be idle would
      be a worse citizen than the problem it fixes.

      LIMITS, worth stating rather than discovering later: this stops IDLE
      transitions only. It does not survive the lid closing, the user choosing
      Sleep, or a battery-critical event — all of which can still suspend a run.
      No explicit release is needed on the normal path because the execution
      state is per-thread and Windows clears it when the process exits; -Release
      exists for callers that keep running after the long work is done.

      Never throws. A job that cannot suppress sleep should still do its work.
    #>
    param([switch]$Release)

    $ES_CONTINUOUS      = [uint32]'0x80000000'
    $ES_SYSTEM_REQUIRED = [uint32]'0x00000001'

    try {
        if (-not ('Whispr.Power' -as [type])) {
            Add-Type -Namespace 'Whispr' -Name 'Power' -MemberDefinition @'
[DllImport("kernel32.dll", SetLastError = true)]
public static extern uint SetThreadExecutionState(uint esFlags);
'@
        }
        $flags = if ($Release) { $ES_CONTINUOUS } else { $ES_CONTINUOUS -bor $ES_SYSTEM_REQUIRED }
        # Returns the PREVIOUS state, or 0 on failure.
        $prev = [Whispr.Power]::SetThreadExecutionState($flags)
        if ($prev -eq 0) {
            Write-Log -Level WARN -Message 'Could not suppress sleep (SetThreadExecutionState returned 0); a long call may still be suspended by standby.'
            return $false
        }
        if ($Release) { Write-Log -Message 'Sleep suppression released.' }
        else          { Write-Log -Message 'Sleep suppression ON for the life of this process (idle standby only; lid-close still sleeps).' }
        return $true
    } catch {
        Write-Log -Level WARN -Message "Could not suppress sleep ($($_.Exception.GetType().Name): $($_.Exception.Message)); continuing anyway."
        return $false
    }
}

# ---------------------------------------------------------------------------
# Failure handling — the "durable trio" (+ best-effort toast), a single
# choke point for every FAIL THE JOB exit in either script.
# ---------------------------------------------------------------------------
function Send-BestEffortToast {
    param([Parameter(Mandatory)][string]$Title, [Parameter(Mandatory)][string]$Message, [string]$NotifierId = 'whispr-sync')
    $shown = $false
    try {
        [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null
        [Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType = WindowsRuntime] | Out-Null
        $template = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText02)
        $textNodes = $template.GetElementsByTagName('text')
        [void]$textNodes.Item(0).AppendChild($template.CreateTextNode($Title))
        [void]$textNodes.Item(1).AppendChild($template.CreateTextNode($Message))
        $toast = [Windows.UI.Notifications.ToastNotification]::new($template)
        $notifier = [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier($NotifierId)
        $notifier.Show($toast)
        $shown = $true
    } catch {
        Write-Log -Level WARN -Message "WinRT toast unavailable (non-fatal): $($_.Exception.Message)"
    }
    if ($shown) { return }
    try {
        $null = & "$env:WINDIR\System32\msg.exe" $env:USERNAME "$Title`: $Message" 2>&1
    } catch {
        Write-Log -Level WARN -Message "msg.exe fallback also unavailable (non-fatal, skipping toast — Event Log + sentinel are the real alert): $($_.Exception.Message)"
    }
}

function Invoke-JobFailure {
    param(
        [Parameter(Mandatory)][string]$StepName,
        [Parameter(Mandatory)][string]$Detail,
        [string]$FileContext = '(n/a)',
        [int]$ExitCode = -1,
        [string]$StdErr = ''
    )
    $timestamp = Get-Date -Format 'yyyy-MM-dd-HHmmss'
    $errorBlock = @"
STEP: $StepName
FILE: $FileContext
EXIT CODE: $ExitCode
DETAIL: $Detail
STDERR:
$StdErr
"@

    Write-Log -Level ERROR -Message "FAIL THE JOB — step '$StepName' failed (file: $FileContext, exit: $ExitCode). $Detail"

    # 1) Sentinel file.
    try {
        $sentinelPath = Join-Path $LogDir "FAILED-$timestamp.txt"
        Write-Utf8File -Path $sentinelPath -Content $errorBlock
    } catch {
        Write-Log -Level ERROR -Message "Could not write failure sentinel: $($_.Exception.Message)"
    }

    # 2) Windows Event Log (best-effort; first-time source creation may need elevation).
    try {
        if (-not [System.Diagnostics.EventLog]::SourceExists($EventLogSource)) {
            New-EventLog -LogName $EventLogName -Source $EventLogSource -ErrorAction Stop
        }
        Write-EventLog -LogName $EventLogName -Source $EventLogSource -EntryType Error -EventId $EventId -Message $errorBlock -ErrorAction Stop
    } catch {
        Write-Log -Level WARN -Message "Could not write to Windows Event Log (may require elevation for first-time source creation; continuing): $($_.Exception.Message)"
    }

    # 3) Best-effort toast (never allowed to mask the real error above).
    # $JobName is set by the caller script (nightly vs weekly); fall back to a
    # generic label so the toast still identifies which job failed.
    $jobLabel = if ($JobName) { $JobName } else { 'whispr-sync' }
    try {
        Send-BestEffortToast -Title "$jobLabel FAILED" -Message "$StepName failed: $Detail" -NotifierId $jobLabel
    } catch {
        Write-Log -Level WARN -Message "Toast notification path threw (non-fatal): $($_.Exception.Message)"
    }

    exit 1
}
